In [1]:
import pandas as pd
import numpy as np

### Load the Data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

### Classification:  2 classes: 1. Moderately Absent - 2. Excessively Absent
#### We will take the median value of the 'Absenteeism Time in Hours' and use it as a cut -off line
#### Everything below the median will be consider NORMAL
#### Everthing above the median will be consider Excesive

#### CREATE TARGETS

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

##### If the observation its been absent for less than 3 hours we will assign with the value of 0 otherwise wthe value of 1
######  In supervised learning we call these 0s and 2s targets, these are the values we are aiming for
###### So, our task will be to predict wether we will obtain a 0 or a 1

In [5]:
## wE CAN USE THE 3 or data_preprocessed['Absenteeism Time in Hours'].median()
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

### Adding the targets

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Comment on the targets
#### Let's divide the total of targets that are 1 between the number of targets.

In [9]:
# total of targets that are 1
targets.sum()

319

In [10]:
# the number of targets
targets.shape[0]

700

In [11]:
targets.sum() / targets.shape[0]

0.45571428571428574

### New Checkpoint

In [12]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 'Daily Work Load Average', 'Distance to Work'],axis=1)

##### Another option to create a checkpoint
##### We can also check if they are different using 'is'

In [13]:
data_with_targets is data_preprocessed

False

In [14]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Select the inputs for the regression

In [15]:
data_with_targets.shape

(700, 12)

#### Select all the columns except Excessive Absenteeism

In [16]:
# data_with_targets.iloc[:,0:14]
# data_with_targets.iloc[:,:14]
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [17]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [18]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

### Standardize the data

In [19]:
!pip install scikit-learn

In [20]:
#from sklearn.preprocessing import StandardScaler

#absenteeism_scaler = StandardScaler()

In [21]:
# from sklearn.base import BaseEstimator, TransformerMixin
# from sklearn.preprocessing import StandardScaler

# class CustomScaler(BaseEstimator,TransformerMixin):
    
#     def __init__(self,columns,copy=True,with_mean=True,with_std=True):
#         self.scaler = StandardScaler(copy,with_mean,with_std)
#         self.columns = columns
#         self.mean_ = None
#         self.var_ = None
    
#     def fit(self, X, y=None):
#         self.scaler.fit(X[self.columns], y)
#         self.mean_ = np.mean(X[self.columns])
#         self.var_ = np.var(X[self.columns])
#         return self
    
#     def transform(self, X, y=None, copy=None):
#         init_col_order = X.columns
#         X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
#         X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
#         return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [22]:
from sklearn.base import BaseEstimator, TransformerMixin

from sklearn.preprocessing import StandardScaler



# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin):

   

    # init or what information we need to declare a CustomScaler object

    # and what is calculated/declared as we do

   

    def __init__(self,columns):   

        # scaler is nothing but a Standard Scaler object

        self.scaler = StandardScaler()

        # with some columns 'twist'

        self.columns = columns

       

   

    # the fit method, which, again based on StandardScale

    def fit(self, X, y=None):

        self.scaler.fit(X[self.columns], y)

        self.mean_ = np.mean(X[self.columns])

        self.var_ = np.var(X[self.columns])

        return self

   

    # the transform method which does the actual scaling

    def transform(self, X, y=None):

        # record the initial order of the columns

        init_col_order = X.columns

       

        # scale all features that you chose when creating the instance of the class

        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)

       

        # declare a variable containing all information that was not scaled

        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]

       

        # return a data frame which contains all scaled features and all 'not scaled' features

        # use the original order (that you recorded in the beginning)

        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [23]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [24]:
##### We'll create a new variable, that will contain the name of the features we want to scale
##### Therefore we will omit the dummy variables from this list

In [25]:
#columns_to_scale = ['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets']
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

#### We are gonna use list comprehension (syntactis construct which allows us to create a list from existing lists based on loops, conditionals, etc.)

In [26]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

#### Technically, the list works like a loop, which looks into all column values and takes those which are not part of the variable columns to omit.

##### Now we can declare the Absenteeism Scaler

In [27]:
absenteeism_scaler = CustomScaler(columns_to_scale)

#### The scaler will be used to subtract the mean and divide by the standard deviation variablewise (featurewise)

#### Next step: fit data

In [59]:
absenteeism_scaler.fit(unscaled_inputs)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3438: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

#### Scaling mechanism - Transform

In [60]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

#### When we get new data we will use:

##### new_data_raw = pd.read_csv('new_data.csv')
##### new_data_scaled = absenteesism_scaler.transform(new_data_raw)

In [61]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.568019   
696         1         0         0         0    -0.568019   
697         1         0         0         0    -0.568019   
698         0         0         0         1    -0.568019   
699         0         0         0         1    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [62]:
scaled_inputs.shape

(700, 11)

### Split the data into train & test and shuffle

#### Import the relevant module

In [63]:
from sklearn.model_selection import train_test_split

#### Split
##### - Everytime you run this, we are gonna get a different split.
##### - AND THEREFORE, A different shuffle.
##### - That is unfortunate, because we may get LUCKY and achieve higher accuracy of the split,
##### - OR, get UNLUCKY and achieve a lower accuracy. CHECK SHUFFLE SECTION BELOW.

In [64]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 207         0         0         1         0    -1.166834   
 444         0         0         0         1     0.330204   
 617         0         0         0         1    -1.466241   
 533         0         0         0         1     0.330204   
 678         0         0         0         1     0.629611   
 ..        ...       ...       ...       ...          ...   
 309         0         0         0         1     0.929019   
 65          0         0         0         1     0.929019   
 325         0         0         0         0     1.228426   
 543         1         0         0         0     1.228426   
 108         0         0         0         1     1.527833   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 207               -0.654143  0.248310         1.002633          0  -0.91903   
 444                0.040034 -1.320435        -0.643782          0  -0.01928   
 617                0.1909

#### Let;s declare 4 variales that will contain the 4 outputs

In [65]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20 )

##### 80% for training and 20% for testing because it was specify before as 0.8

In [66]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [67]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


### THE SPLIT

#### - Everytime you run this, we are gonna get a different split.
#### - AND THEREFORE, A different shuffle.
#### - That is unfortunate, because we may get LUCKY and achieve higher accuracy of the split,
#### - OR, get UNLUCKY and achieve a lower accuracy. CHECK SHUFFLE SECTION BELOW.

##### Usually, we opt for splits like 90-10 or 80-20 (because we want to train on more data)

##### - how do we do this? going back and specific it:

#####  - x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8)
#####  - This means that 80% will be use for training and 20% for testing.

### THE SHUFFLE

#### ** the TRAIN TEST SPLIT METHOD has a Shuffle which is a boolean value that is  set to TRUE BY DEFAULT
#####          - Shuffle is a Boolean value, so it can be true or false
#####          - All SKLEARN  functions that include some randomness, like this random shuffle, contain a  RANDOM_STARTE parameter
#####          - random_state takes integer values, if we set it to 20, it will always shuffle the observations in the same "random" way

## Logistic Regression with SKLEARN

In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [69]:
reg = LogisticRegression()

In [70]:
reg.fit(x_train,y_train)

LogisticRegression()

### This is our Train Accuracy

In [71]:
reg.score(x_train,y_train)

0.7767857142857143

### Manually check the accuracy

#### Let's find out the model outputs
##### This method will find the predictited output of the regression

In [72]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

#### Is this the same as the model outputs??

In [73]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

#### Let's find out!

In [74]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

##### But how many are they?

In [75]:
np.sum(model_outputs == y_train) ## This is the total number of True entries

435

#### We can find the Accuracy dividing the total number of matches by the total number of Elements
##### We can find the toatl number of elements using xx.shape[0]

In [76]:
model_outputs.shape[0]

560

In [77]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.7767857142857143

#### As results, the same number using the " reg.score(x_train,y_train) " method. But now,
#### with much better idea of what that result means exactly! 

### ==============================================================

### MORE LOGISTIC REGRESSION

### ==============================================================

### Finding the intercept and coefficients

In [78]:
reg.intercept_

array([-1.60957471])

In [79]:
reg.coef_

array([[ 2.77151176,  0.93168817,  3.09210221,  0.8090592 ,  0.00781237,
         0.62505482, -0.17390339,  0.28829409, -0.24081615,  0.35753531,
        -0.27337422]])

In [80]:
scaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

##### REMINDER: when a ndarray function is used, everything is transformod to arrays.
##### So, I'll be using unscaled inputs to find the column names, because that one is still a pandas Dataframe

In [81]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

##### New variable that contains this info

In [82]:
feature_name = unscaled_inputs.columns.values

##### Neat dataframe that contains the intercept, the feature names and the corresponding cohefficients

In [83]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)


In [84]:
summary_table

Feature name  Coefficient
0                 Reason_1     2.771512
1                 Reason_2     0.931688
2                 Reason_3     3.092102
3                 Reason_4     0.809059
4              Month Value     0.007812
5   Transportation Expense     0.625055
6                      Age    -0.173903
7          Body Mass Index     0.288294
8                Education    -0.240816
9                 Children     0.357535
10                    Pets    -0.273374

##### REMINDER: ndarrays are ROWS, not columns!
##### reg.coef_

##### Let's add one to all indices of the dataframe summary table.

In [85]:
## Moving the indexes 1 space up
summary_table.index = summary_table.index + 1

## Adding the Intercept to index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

## Sorting by index
summary_table = summary_table.sort_index()

In [86]:
summary_table

Feature name  Coefficient
0                Intercept    -1.609575
1                 Reason_1     2.771512
2                 Reason_2     0.931688
3                 Reason_3     3.092102
4                 Reason_4     0.809059
5              Month Value     0.007812
6   Transportation Expense     0.625055
7                      Age    -0.173903
8          Body Mass Index     0.288294
9                Education    -0.240816
10                Children     0.357535
11                    Pets    -0.273374

### Interpreting the Coefficients
#### coefficient = weight
#### intercept   = bias

### Whenever we are dealing with Logistic Regression, the coefficients we are predicting are the so-called LOG ODDS!
### logistic Regression by default are nothing but a linear function predicting log odds.
### These log odds are later transformed into zeros and ones.

In [87]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [88]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.609575    0.199973
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
3                 Reason_3     3.092102   22.023327
4                 Reason_4     0.809059    2.245794
5              Month Value     0.007812    1.007843
6   Transportation Expense     0.625055    1.868348
7                      Age    -0.173903    0.840378
8          Body Mass Index     0.288294    1.334150
9                Education    -0.240816    0.785986
10                Children     0.357535    1.429801
11                    Pets    -0.273374    0.760808

In [89]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.092102   22.023327
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
4                 Reason_4     0.809059    2.245794
6   Transportation Expense     0.625055    1.868348
10                Children     0.357535    1.429801
8          Body Mass Index     0.288294    1.334150
5              Month Value     0.007812    1.007843
7                      Age    -0.173903    0.840378
9                Education    -0.240816    0.785986
11                    Pets    -0.273374    0.760808
0                Intercept    -1.609575    0.199973

### Interpreting the important Predictors

#### -	The further away from 0 coefficient is, the bigger its importance
#### -	Looking at the coefficients table, I can notice that the most strongly pronounced features are the four reasons for absence, transportation expense and whether a person has a children, pet or education.
#### -	Pet and education are the bottom of the table, but their weights are still far away from ZERO. They are indeed important
#### -	The daily workload, distance to work, and day of the week, which seem to have the smallest impact, their weight is almost zero. So, regardless of the particular values, they will barely affect out model
#### -	The Reasons? The model includes no reason, but what is the impact of the various reasons?
#####       o	Reason 1: various diseases
#####       o	Reason 2: pregnancy and giving birth
#####       o	Reason 3: poisoning
#####       o	Reason 4: light diseases
#### -	The most crucial reason for excessive absence is poisoning; kinda obvious; if you are poisoned, you won’t go to work
#### -	Reason 1, is a very important reason for our model; this is the normal absenteeism case, you are sick, and you skipped work.
#### -	Reason 2, It is obviously the fact that many women won’t be able to work in this situation, It is a prominent cause of absenteeism, but it is way less pronounced than reasons 1 and 3.
#### -	Transportation Expense: This is the most important NON-DUMMY feature in the model. BUT! it is one of our standardized variables, we don’t have direct interpretability of it.
#####       o	Its odds ratio implies that for one standardized unit or for one standard deviation increase in transportation expense, it is close to twice as likely to be excessively absent.
#####       o	This is the main drawback of standardization, standardized models almost always yield higher accuracy because the optimization algorithms work better, 
#### -	Machine learning Engineers: They prefer models with higher accuracy, so they normally go for standardization
#### -	Econometricians and Statisticians: prefer less accurate but more interpretable models because they care about the underlying reason behind different phenomena.
#### -	Data Scientists: Either position, Sometimes, we need higher accuracy, other times – we must find the main drivers of a problem.
#### -	So, it is a good practice to create two different models, one with standardized features and one without them and then draw insights from both.
#### -	For predicting values, it is preferred higher accuracy. That means, standardization is often the norm
#### -	This project has been worked on the Data Scientist’s point of view, checking both sides of the coin.
#### -	Pet, it is a continuous variable. Its odds ratio is 0.7, so for each additional standardized unit of Pet, the odds are one minus its odds ratio or twenty-four percent lower than the base bottle. One explanation may be if you have several pets, you’re probably not taking care of them on your own.
#### -	Children: second more important NON-DUMMY feature in the mode. If the person is responsible of taking care of their children, it’s more likely that they skipped work.
#### -	Body Mass Index: It is hard to determine if this variable is really impactful on the model because we would have to have more information about the body weight of each employee, but it is the third NON-DUMMY variable more important after Children.
#### -	The Intercept: it is used to get more accurate predictions, but there’s no specific meaning attached to it. In Machine Learning, you can say that it calibrates the model, and you can also call it BIAS.
#####       o	Nevertheless, without an intercept, each prediction would be off the mark by precisely that value.


### Simplifying the Model - Backward Elimination

#### Backward Elimination: We can simplify our model by removing all features which have close to no contribution to the model.
#### When we have the p*values, we get rid of all coefficients with p*values > 0.05
#### NOTE: with Sklearn, we don't have p-values, because we don't necessarily need them. The reasoning of the engineers who created the package is that if the weight is small enough,
#### It won't make a difference anyway. Let's trust them =).
#### So, if I remove these variables, the rest of our model should not really change in terms of coefficient values.

## Testing the Model

#### Our algorithm hass seen our train data thousands of times during the training process. It has learned to model it quite well.
#### BUT, It may fail miserably when provided with new data. So,
#### Gotta test it with data it has never seen.

### It's time to use the Test Data

In [90]:
reg.score(x_test,y_test)

0.7357142857142858

In [92]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.75466347, 0.24533653],
       [0.60917591, 0.39082409],
       [0.48329093, 0.51670907],
       [0.75768232, 0.24231768],
       [0.08357741, 0.91642259],
       [0.3052464 , 0.6947536 ],
       [0.303675  , 0.696325  ],
       [0.11636888, 0.88363112],
       [0.7400284 , 0.2599716 ],
       [0.75596036, 0.24403964],
       [0.50609784, 0.49390216],
       [0.19501503, 0.80498497],
       [0.06248668, 0.93751332],
       [0.7055465 , 0.2944535 ],
       [0.29675526, 0.70324474],
       [0.52028649, 0.47971351],
       [0.50551315, 0.49448685],
       [0.50843643, 0.49156357],
       [0.36713074, 0.63286926],
       [0.06422143, 0.93577857],
       [0.73822433, 0.26177567],
       [0.75768232, 0.24231768],
       [0.47994423, 0.52005577],
       [0.47760936, 0.52239064],
       [0.22619725, 0.77380275],
       [0.74047815, 0.25952185],
       [0.51148533, 0.48851467],
       [0.87702735, 0.12297265],
       [0.24005377, 0.75994623],
       [0.75768232, 0.24231768],
       [0.

#### First Columns is the observation of the probability being 0, and the second column is the observation of the probability being 1.
#### That's why summing any two number horizontally will give you an output of 1

In [93]:
predicted_proba.shape

(140, 2)

#### What we are inteested in is a probability of excessive absenteeism.
#### Therefore, we can simply slice out all values from the second column
#### This will give us the probabilities of excessive absenteeism and this result is way better than 0s and 1s

In [94]:
predicted_proba[:,1]

array([0.24533653, 0.39082409, 0.51670907, 0.24231768, 0.91642259,
       0.6947536 , 0.696325  , 0.88363112, 0.2599716 , 0.24403964,
       0.49390216, 0.80498497, 0.93751332, 0.2944535 , 0.70324474,
       0.47971351, 0.49448685, 0.49156357, 0.63286926, 0.93577857,
       0.26177567, 0.24231768, 0.52005577, 0.52239064, 0.77380275,
       0.25952185, 0.48851467, 0.12297265, 0.75994623, 0.24231768,
       0.38859882, 0.71238179, 0.69821485, 0.49507156, 0.24231768,
       0.59772596, 0.26042186, 0.78022686, 0.4398591 , 0.60641126,
       0.24188848, 0.49713003, 0.25862385, 0.40689715, 0.80759194,
       0.59889345, 0.71944702, 0.24317762, 0.24676126, 0.2414598 ,
       0.50180816, 0.29299268, 0.6947536 , 0.24459387, 0.82033268,
       0.39193844, 0.90599346, 0.26442957, 0.32150234, 0.3220128 ,
       0.70502976, 0.69623972, 0.26579672, 0.77584327, 0.24541121,
       0.24490372, 0.07551158, 0.26087263, 0.76176924, 0.29640101,
       0.25772789, 0.31539593, 0.88408057, 0.4387068 , 0.59547

#### In reality, logistic regression models calculate these probabilities in thebackground.
#### If the probability is:
#### -> below 0.5, it places a 0
#### -> above 0.5, it places a 1

## Save the Model

###  This is the process of creating a file that will contain all the information regarding the machine learning.
#### Saving the model = Saving the reg object

### Let's use pickle [module]: which is a python module used to convert a python object into a character stream

In [96]:
import pickle

In [98]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

##### We have to save the Standard Scaler as well
##### Why? because our code was heavily dependent on training data without training data, the machine learning could not be executed at all.
##### But, once the model is trained and we have obtained the coefficients, we can save it as we just have
##### Basically, we are separating the model from the training data for good.

##### In other words, the information in the absenteeism scaler is needed to pre-process any new data, using the same rules as the ones applied to trading data.
##### THUS, we must pickle the scaler as well.

In [101]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)